# Generated by Django 5.2.4 on 2025-07-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_company_user_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_active',
            field=models.BooleanField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('none', 'بدون اشتراک'), ('bronze', 'برنزی'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی')], default='none', max_length=20),
        ),
    ]
