# Generated by Django 4.2.7 on 2025-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_subscription_active_user_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
