# Generated by Django 4.2.7 on 2025-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_subscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
