# Generated by Django 4.2.7 on 2025-08-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
