# Generated by Django 4.2.7 on 2025-08-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_is_admin_alter_user_subscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('pending_review', 'در حال بررسی'), ('active', 'فعال'), ('inactive', 'غیرفعال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('rejected', 'رد شده')], default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('auction_start', 'شروع مزایده'), ('auction_end', 'پایان مزایده'), ('new_bid', 'پیشنهاد جدید'), ('won_auction', 'برنده شدن در مزایده'), ('outbid', 'پیشنهاد بالاتر'), ('auction_created', 'مزایده ایجاد شد'), ('tender_created', 'مناقصه ایجاد شد'), ('auction_approved', 'مزایده تایید شد'), ('tender_approved', 'مناقصه تایید شد'), ('auction_rejected', 'مزایده رد شد'), ('tender_rejected', 'مناقصه رد شد'), ('pending_approval', 'در انتظار تایید')], max_length=20),
        ),
    ]
